# Generated by Django 4.2.5 on 2023-09-22 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_order_cart_order_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
