# Generated by Django 4.2.5 on 2023-09-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_cart_category_user_date_of_birth_user_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.ManyToManyField(to='website.cartitem'),
        ),
    ]
