# Generated by Django 4.2.5 on 2023-09-26 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='C:\\Users\\User\\OneDrive\\Documentos\\projects\\rumos\\rumos-project\\media\\static\\default.png', upload_to='uploads/product/'),
        ),
    ]
