# Generated by Django 4.2.5 on 2023-09-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_product_category_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='C:\\Users\\User\\OneDrive\\Documentos\\projects\\rumos\\rumos-project\\static\\default.png', upload_to='uploads/product/'),
        ),
    ]
