# Generated by Django 4.2.5 on 2023-09-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='C:\\Users\\User\\OneDrive\\Documentos\\projects\\rumos\\rumosproject\\media\\uploads\\default.png', upload_to='media/uploads/product/'),
        ),
    ]
