# Generated by Django 4.2.5 on 2023-09-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='website.CartItem', to='website.product'),
        ),
    ]
