# Generated by Django 4.2.5 on 2023-10-02 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_orderitem_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.order'),
        ),
    ]
