# Generated by Django 4.2.5 on 2023-10-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='static/uploads/challenge/')),
                ('answer', models.CharField(max_length=255)),
            ],
        ),
    ]
