# Generated by Django 4.2.5 on 2023-10-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_challenge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='answer',
            new_name='user_answer',
        ),
        migrations.AddField(
            model_name='challenge',
            name='correct_answer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
