# Generated by Django 4.2.5 on 2023-10-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_rename_answer_challenge_user_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='correct_answer',
            field=models.CharField(max_length=255),
        ),
    ]
