# Generated by Django 4.2.5 on 2023-10-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_challenge_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='user_answer',
        ),
    ]
