# Generated by Django 4.2.5 on 2023-10-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_remove_challenge_user_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
