# Generated by Django 4.2.5 on 2023-10-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_remove_address_user_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
